embrapa:
  url_base: "http://vitibrasil.cnpuv.embrapa.br/index.php?"
  data_max: 2023
  data_min: 1970

data_of_interest:
  production:
    opc: "&opcao=opt_02"

  processing:
    opc: "opcao=opt_03"
    viniferas: "&subopcao=subopt_01"
    americana_hibri: "&subopcao=subopt_02"
    uva_mesa: "&subopcao=subopt_03"
    sem_class: "&subopcao=subopt_04"

  commercialization:
    url: "&opcao=opt_04"

  importation:
    opc: "&opcao=opt_05"
    vinho_mesa: "&subopcao=subopt_01"
    espumante: "&subopcao=subopt_02"
    uvas_frescas: "&subopcao=subopt_03"
    uvas_passas: "&subopcao=subopt_04"
    suco_uva: "&subopcao=subopt_05"

  exportation:
    opc: "opcao=opt_06"
    vinho_mesa: "&subopcao=subopt_01"
    espumante: "&subopcao=subopt_02"
    uvas_frescas: "&subopcao=subopt_03"
    suco_uva: "&subopcao=subopt_04"



